-- 코드를 입력하세요
SELECT
    C.CAR_ID AS CAR_ID,
    C.CAR_TYPE AS CAR_TYPE,
    ROUND(C.DAILY_FEE - C.DAILY_FEE * P.DISCOUNT_RATE / 100) * 30 AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
    AND DURATION_TYPE = '30일 이상'
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
GROUP BY
    C.CAR_ID
HAVING
    0 = SUM('2022-11-01' BETWEEN H.START_DATE AND H.END_DATE) + 
    SUM('2022-11-30' BETWEEN H.START_DATE AND H.END_DATE)
    AND FEE BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC, CAR_TYPE, CAR_ID DESC