SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
    ROUND(
        (COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021')),
        1
    ) AS PUCHASED_RATIO
FROM
    ONLINE_SALE AS S
LEFT JOIN
    USER_INFO AS U
    ON S.USER_ID = U.USER_ID
WHERE
    YEAR(U.JOINED) = '2021'
GROUP BY
    MONTH
ORDER BY
    YEAR, MONTH;
    