SELECT
    ITEM.ITEM_ID,
    ITEM.ITEM_NAME,
    ITEM.RARITY
FROM
    ITEM_INFO AS ITEM
LEFT JOIN
    ITEM_TREE AS TREE
    ON ITEM.ITEM_ID = TREE.PARENT_ITEM_ID
WHERE
    TREE.PARENT_ITEM_ID IS NULL
ORDER BY
    ITEM.ITEM_ID DESC