SELECT
    T.ID,
    CASE 
        WHEN T.SIZE_PERCENT <= 25 THEN 'CRITICAL'
        WHEN T.SIZE_PERCENT <= 50 THEN 'HIGH'
        WHEN T.SIZE_PERCENT <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        CUME_DIST() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 AS SIZE_PERCENT
    FROM
        ECOLI_DATA
) AS T
ORDER BY
    T.ID