WITH RECURSIVE GENERATIONS AS (
    SELECT
        ID, 
        PARENT_ID,
        EXISTS(SELECT 1 FROM ECOLI_DATA AS A WHERE A.PARENT_ID = E.ID) AS HAS_CHILD,
        1 AS GENERATION
    FROM
        ECOLI_DATA AS E
    WHERE
        PARENT_ID IS NULL
    UNION ALL
    SELECT
        E.ID,
        E.PARENT_ID,
        EXISTS(SELECT 1 FROM ECOLI_DATA AS A WHERE A.PARENT_ID = E.ID) AS HAS_CHILD,
        G.GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA AS E
    INNER JOIN
        GENERATIONS AS G
        ON E.PARENT_ID = G.ID
)

SELECT 
    COUNT(*) AS `COUNT`,
    GENERATION
FROM
    GENERATIONS
WHERE
    HAS_CHILD = FALSE
GROUP BY
    GENERATION
    
    
    