WITH RECURSIVE Generation_CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN Generation_CTE g ON e.PARENT_ID = g.ID
)
SELECT  COUNT(*) AS COUNT, GENERATION
FROM Generation_CTE g
WHERE NOT EXISTS (
    SELECT 1 
    FROM ECOLI_DATA e 
    WHERE e.PARENT_ID = g.ID
)
GROUP BY GENERATION
ORDER BY GENERATION;