SELECT
    *
FROM (
    SELECT
        CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q')  AS QUARTER,
        COUNT(*) AS ECOLI_COUNT
    FROM
        ECOLI_DATA
    GROUP BY
        QUARTER
) AS T
ORDER BY
    T.QUARTER