-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    CATEGORY,
    SUM(S.SALES * PRICE) AS TOTALSALES
FROM
    BOOK_SALES AS S
LEFT JOIN
    BOOK AS B
    ON S.BOOK_ID = B.BOOK_ID
LEFT JOIN
    AUTHOR AS A
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE
    S.SALES_DATE LIKE ('2022-01%')
GROUP BY
    A.AUTHOR_ID, B.CATEGORY
ORDER BY
    AUTHOR_ID, CATEGORY DESC