-- 코드를 입력하세요
SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO AS I
LEFT JOIN
    FIRST_HALF AS H
    ON I.FLAVOR = H.FLAVOR
GROUP BY
    I.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER