SELECT
    CHILD.ID,
    CHILD.GENOTYPE,
    PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS CHILD
INNER JOIN
    ECOLI_DATA AS PARENT
    ON PARENT.ID = CHILD.PARENT_ID
    AND PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE
ORDER BY
    CHILD.ID