WITH MAX_SIZE_OF_COLONY AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)    
)

SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (
        (SELECT MAX_SIZE 
         FROM MAX_SIZE_OF_COLONY 
         WHERE YEAR = YEAR(ECOLI.DIFFERENTIATION_DATE)
        ) - SIZE_OF_COLONY
    ) AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA AS ECOLI
ORDER BY
    YEAR(DIFFERENTIATION_DATE), YEAR_DEV