SELECT
    RANK_FISH.ID,
    FISH_NAME_INFO.FISH_NAME,
    RANK_FISH.LENGTH
FROM (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS LENGTH_RANK
    FROM
        FISH_INFO
) AS RANK_FISH
INNER JOIN
    FISH_NAME_INFO
    ON RANK_FISH.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE
    RANK_FISH.LENGTH_RANK = 1
ORDER BY
    ID